<!DOCTYPE html>
<html lang="en"><head>
<script src="builders_files/libs/clipboard/clipboard.min.js"></script>
<script src="builders_files/libs/quarto-html/tabby.min.js"></script>
<script src="builders_files/libs/quarto-html/popper.min.js"></script>
<script src="builders_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="builders_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="builders_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="builders_files/libs/quarto-html/quarto-syntax-highlighting-b6a8276bf55561bdbc268162d41bd1f7.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.30">

  <meta name="author" content="Oleg Lugovoy, et al.">
  <title>Building blocks of an energyRt model</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="builders_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="builders_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="builders_files/libs/revealjs/dist/theme/quarto-0427d8d92a431aa6a6430e53ec02a470.css">
  <link href="builders_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="builders_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="builders_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="builders_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Building blocks of an energyRt model</h1>
  <p class="subtitle">The <code>new*()</code> constructors, and the system around them</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Oleg Lugovoy, et al. 
</div>
</div>
</div>

</section>
<section class="slide level2">

<style>
.badge {
  font-size: 0.62em; font-weight: 600; letter-spacing: .04em;
  padding: .10em .45em; border-radius: .35em; vertical-align: middle;
  text-transform: uppercase; white-space: nowrap;
}
.exp     { background: #fdf0d5; color: #8a5a00; border: 1px solid #e8c98a; }
.planned { background: #eef2f7; color: #3d5a80; border: 1px solid #b8c9dd; }
.limited { background: #fbe9e7; color: #9c3a2e; border: 1px solid #e8b4ac; }

/* Buy vertical room from SPACING, not from type size, so the text stays big. */
.reveal h2            { font-size: 1.5em; margin-bottom: .35em; }
.reveal section p     { margin: .38em 0; line-height: 1.28; }
/* Only touch top/bottom: a shorthand `margin: .25em 0` would zero the LEFT
   margin too, and that is where ordered-list numbers are drawn -- they end up
   outside the column box and get clipped. */
.reveal ul, .reveal ol { margin-top: .25em; margin-bottom: .25em; line-height: 1.3; }
.reveal ol            { list-style-position: outside; }
.reveal li            { margin-top: .18em; margin-bottom: .18em; }
.reveal li > ul       { margin-top: .1em; margin-bottom: .1em; }
/* Columns clip their overflow, so give a list inside one room for its markers. */
.reveal .column ol,
.reveal .column ul    { padding-left: 1.2em; }
.reveal .columns      { gap: .8em; }
.reveal pre           { margin: .45em 0; box-shadow: none; }
.reveal pre code      { padding: .5em .7em; line-height: 1.24; }
.reveal blockquote    { margin: .5em 0; }
.reveal .callout      { margin: .5em 0; font-size: .88em; }

/* Tables: readable by default; .small-table only for the reference matrices. */
.reveal table              { font-size: .9em; margin: .4em 0; }
.reveal table th,
.reveal table td           { padding: .18em .5em; }
.reveal .small-table table { font-size: .74em; }

/* `{.smaller}` is reveal's 0.6x. That is too aggressive here -- soften it so
   dense slides shrink a little instead of a lot. */
.reveal section.smaller > h2 { font-size: 1.4em; }
.reveal .smaller           { font-size: 0.86em; }
</style>
<aside class="notes">
<p>Reference deck. Parts 1 and 6 are the live-teaching core; the rest is written to be browsable afterwards. Badges: experimental / planned / backend-limited.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="the-bricks" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>1 · The bricks</h1>

</section>
<section id="the-vocabulary" class="slide level2 smaller">
<h2>The vocabulary</h2>
<p>An energyRt model is a <strong>set of objects</strong>, each built by a <code>new*()</code> function.</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Commodities</strong> — the things that flow</p>
<ul>
<li><code>newCommodity()</code></li>
</ul>
<p><strong>Processes</strong> — the things that move or transform them</p>
<ul>
<li><code>newSupply()</code>, <code>newImport()</code>, <code>newExport()</code></li>
<li><code>newDemand()</code></li>
<li><code>newTechnology()</code></li>
<li><code>newStorage()</code>, <code>newTrade()</code></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Containers</strong> — how they are assembled</p>
<ul>
<li><code>newRepository()</code> — a bag of objects</li>
<li><code>newHorizon()</code> — the years</li>
<li><code>newModel()</code> — objects + regions + horizon</li>
</ul>
<p><strong>Policy</strong> <em>(later chapters)</em></p>
<ul>
<li><code>newConstraint()</code>, <code>newTax()</code>, <code>newSubsidy()</code></li>
</ul>
</div></div>
<div class="fragment">
<p>Every process can be <strong>drawn</strong>: <code>draw(obj)</code> sketches its flows. We use it on every slide from here on.</p>
</div>
</section>
<section id="one-grammar-everywhere" class="slide level2 smaller">
<h2>One grammar, everywhere</h2>
<p>Every constructor follows the same shape:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">newTechnology</span>(</span>
<span id="cb1-2"><a href=""></a>  <span class="at">name    =</span> <span class="st">"ECOA"</span>,              <span class="co"># the set element -- UPPERCASE, no spaces</span></span>
<span id="cb1-3"><a href=""></a>  <span class="at">desc    =</span> <span class="st">"Coal power plant"</span>,  <span class="co"># free text</span></span>
<span id="cb1-4"><a href=""></a>  <span class="at">input   =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"COA"</span>),  <span class="co"># what it consumes</span></span>
<span id="cb1-5"><a href=""></a>  <span class="at">output  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>),  <span class="co"># what it produces</span></span>
<span id="cb1-6"><a href=""></a>  <span class="at">ceff    =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"COA"</span>, <span class="at">cinp2use =</span> <span class="fl">0.4</span>),   <span class="co"># parameters</span></span>
<span id="cb1-7"><a href=""></a>  <span class="at">region  =</span> <span class="fu">character</span>()          <span class="co"># empty = every region</span></span>
<span id="cb1-8"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<ul>
<li><strong><code>name</code></strong> is the identifier the solver sees.</li>
<li><strong>Parameters are <code>data.frame</code>s</strong>, and may carry <code>region</code>, <code>year</code>, <code>slice</code> columns. Leave a column out and the value applies to <em>all</em> of them.</li>
<li>Values between given years are <strong>interpolated</strong> — you supply anchors, not a full grid.</li>
</ul>
</section>
<section id="newcommodity-what-flows" class="slide level2 smaller">
<h2><code>newCommodity()</code> — what flows</h2>
<p>A commodity is a <em>label with a unit</em>. It has no diagram: it is the thing that travels along the arrows, not a box.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>COA <span class="ot">&lt;-</span> <span class="fu">newCommodity</span>(</span>
<span id="cb2-2"><a href=""></a>  <span class="at">name      =</span> <span class="st">"COA"</span>,</span>
<span id="cb2-3"><a href=""></a>  <span class="at">desc      =</span> <span class="st">"Coal"</span>,</span>
<span id="cb2-4"><a href=""></a>  <span class="at">unit      =</span> <span class="st">"PJ"</span>,</span>
<span id="cb2-5"><a href=""></a>  <span class="at">timeframe =</span> <span class="st">"ANNUAL"</span>,                     <span class="co"># ANNUAL | HOUR | ...</span></span>
<span id="cb2-6"><a href=""></a>  <span class="at">emis      =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"CO2"</span>,      <span class="co"># released when burned</span></span>
<span id="cb2-7"><a href=""></a>                         <span class="at">unit =</span> <span class="st">"kt/PJ"</span>,</span>
<span id="cb2-8"><a href=""></a>                         <span class="at">emis =</span> <span class="dv">95</span>)</span>
<span id="cb2-9"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong><code>timeframe</code></strong> — the finest resolution at which this commodity balances. <code>ANNUAL</code> pools the year; <code>HOUR</code> forces hourly balancing.</li>
<li><strong><code>emis</code></strong> — emission factors travel with the <em>fuel</em>, so every technology that burns it inherits them (given <code>combustion = 1</code> on the input).</li>
</ul>
</section>
<section id="newsupply-a-domestic-resource" class="slide level2 smaller">
<h2><code>newSupply()</code> — a domestic resource</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a>SUP_COA <span class="ot">&lt;-</span> <span class="fu">newSupply</span>(</span>
<span id="cb3-2"><a href=""></a>  <span class="at">name      =</span> <span class="st">"SUP_COA"</span>,</span>
<span id="cb3-3"><a href=""></a>  <span class="at">desc      =</span> <span class="st">"Coal supply"</span>,</span>
<span id="cb3-4"><a href=""></a>  <span class="at">commodity =</span> <span class="st">"COA"</span>,</span>
<span id="cb3-5"><a href=""></a>  <span class="at">unit      =</span> <span class="st">"PJ"</span>,</span>
<span id="cb3-6"><a href=""></a>  <span class="at">supply    =</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-7"><a href=""></a>    <span class="at">cost   =</span> <span class="fl">2.5</span>,      <span class="co"># MEUR/PJ</span></span>
<span id="cb3-8"><a href=""></a>    <span class="at">ava.up =</span> <span class="dv">500</span>       <span class="co"># cap, PJ/year</span></span>
<span id="cb3-9"><a href=""></a>  )</span>
<span id="cb3-10"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>supply</code> accepts <code>cost</code> and the availability bounds <code>ava.lo</code> / <code>ava.up</code> / <code>ava.fx</code>, plus optional <code>region</code>, <code>year</code>, <code>slice</code>.</p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-4-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="newdemand-what-must-be-served" class="slide level2 smaller">
<h2><code>newDemand()</code> — what must be served</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a>DEM_ELC <span class="ot">&lt;-</span> <span class="fu">newDemand</span>(</span>
<span id="cb4-2"><a href=""></a>  <span class="at">name      =</span> <span class="st">"DEM_ELC"</span>,</span>
<span id="cb4-3"><a href=""></a>  <span class="at">desc      =</span> <span class="st">"Electricity demand"</span>,</span>
<span id="cb4-4"><a href=""></a>  <span class="at">commodity =</span> <span class="st">"ELC"</span>,</span>
<span id="cb4-5"><a href=""></a>  <span class="at">unit      =</span> <span class="st">"PJ"</span>,</span>
<span id="cb4-6"><a href=""></a>  <span class="at">demand    =</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-7"><a href=""></a>    <span class="at">year   =</span> <span class="fu">c</span>(<span class="dv">2025</span>, <span class="dv">2050</span>),</span>
<span id="cb4-8"><a href=""></a>    <span class="at">demand =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">80</span>)</span>
<span id="cb4-9"><a href=""></a>  )</span>
<span id="cb4-10"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Demand is <strong>exogenous</strong>: it is a constraint, not a choice. Values between 2025 and 2050 are interpolated.</p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-6-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="newimport-a-flow-from-outside" class="slide level2 smaller">
<h2><code>newImport()</code> — a flow from outside</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>IMP_GAS <span class="ot">&lt;-</span> <span class="fu">newImport</span>(</span>
<span id="cb5-2"><a href=""></a>  <span class="at">name      =</span> <span class="st">"IMP_GAS"</span>,</span>
<span id="cb5-3"><a href=""></a>  <span class="at">desc      =</span> <span class="st">"LNG import"</span>,</span>
<span id="cb5-4"><a href=""></a>  <span class="at">commodity =</span> <span class="st">"GAS"</span>,</span>
<span id="cb5-5"><a href=""></a>  <span class="at">unit      =</span> <span class="st">"PJ"</span>,</span>
<span id="cb5-6"><a href=""></a>  <span class="at">import    =</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-7"><a href=""></a>    <span class="at">price  =</span> <span class="fl">9.0</span>,     <span class="co"># MEUR/PJ</span></span>
<span id="cb5-8"><a href=""></a>    <span class="at">imp.up =</span> <span class="dv">200</span>      <span class="co"># cap, PJ/year</span></span>
<span id="cb5-9"><a href=""></a>  ),</span>
<span id="cb5-10"><a href=""></a>  <span class="at">reserve   =</span> <span class="dv">3000</span>    <span class="co"># cumulative cap</span></span>
<span id="cb5-11"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>newExport()</code> is its mirror: <code>export</code>, <code>price</code>, <code>exp.up</code>.</p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-8-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="newtechnology-the-converter" class="slide level2 smaller">
<h2><code>newTechnology()</code> — the converter</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a>ECOA <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb6-2"><a href=""></a>  <span class="at">name    =</span> <span class="st">"ECOA"</span>,</span>
<span id="cb6-3"><a href=""></a>  <span class="at">desc    =</span> <span class="st">"Coal power plant"</span>,</span>
<span id="cb6-4"><a href=""></a>  <span class="at">input   =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"COA"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>,</span>
<span id="cb6-5"><a href=""></a>                 <span class="at">combustion =</span> <span class="dv">1</span>),</span>
<span id="cb6-6"><a href=""></a>  <span class="at">output  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>),</span>
<span id="cb6-7"><a href=""></a>  <span class="at">ceff    =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"COA"</span>,</span>
<span id="cb6-8"><a href=""></a>                       <span class="at">cinp2use =</span> <span class="fl">0.40</span>),</span>
<span id="cb6-9"><a href=""></a>  <span class="at">invcost =</span> <span class="fu">list</span>(<span class="at">invcost =</span> <span class="dv">2000</span>),  <span class="co"># MEUR/GW</span></span>
<span id="cb6-10"><a href=""></a>  <span class="at">fixom   =</span> <span class="dv">55</span>, <span class="at">cap2act =</span> <span class="fl">31.536</span>,</span>
<span id="cb6-11"><a href=""></a>  <span class="at">olife   =</span> <span class="dv">30</span>L</span>
<span id="cb6-12"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-10-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p>Read the diagram left to right: <strong><code>inp</code> → <code>use</code> → <code>act</code> → <code>out</code></strong>.</p>
</section>
<section id="the-five-stages" class="slide level2 smaller">
<h2>The five stages</h2>
<p>Every technology has the same internal chain. Each arrow is a coefficient:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Stage</th>
<th>Meaning</th>
<th>Coefficient</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>inp</code></td>
<td>commodity entering</td>
<td>—</td>
</tr>
<tr class="even">
<td><code>ginp</code></td>
<td><em>grouped</em> input, if declared</td>
<td><code>cinp2ginp</code></td>
</tr>
<tr class="odd">
<td><code>use</code></td>
<td>what the process actually consumes</td>
<td><code>cinp2use</code>, <code>ginp2use</code></td>
</tr>
<tr class="even">
<td><code>act</code></td>
<td>activity — the capacity-linked variable</td>
<td><code>use2cact</code></td>
</tr>
<tr class="odd">
<td><code>out</code></td>
<td>commodity leaving</td>
<td><code>cact2cout</code></td>
</tr>
</tbody>
</table>
<div class="fragment">
<ul>
<li><strong><code>cap2act</code></strong> converts capacity into annual activity (1 GW × 8760 h = 31.536 PJ).</li>
<li>Give <strong>one</strong> efficiency coefficient and the rest default to 1 — that is why <code>cinp2use = 0.40</code> alone describes a 40 % plant.</li>
</ul>
</div>
</section>
<section id="grouped-input-co-firing" class="slide level2 smaller">
<h2>Grouped input: co-firing</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p>Two fuels feeding <strong>one</strong> boiler. The group is the thing with an efficiency; the members compete for share within it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a>ECOFIRE <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb7-2"><a href=""></a>  <span class="at">name   =</span> <span class="st">"ECOFIRE"</span>,</span>
<span id="cb7-3"><a href=""></a>  <span class="at">input  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="fu">c</span>(<span class="st">"COA"</span>, <span class="st">"BIO"</span>),</span>
<span id="cb7-4"><a href=""></a>                <span class="at">unit =</span> <span class="fu">c</span>(<span class="st">"PJ"</span>, <span class="st">"PJ"</span>),</span>
<span id="cb7-5"><a href=""></a>                <span class="at">group =</span> <span class="fu">c</span>(<span class="st">"FUEL"</span>, <span class="st">"FUEL"</span>),</span>
<span id="cb7-6"><a href=""></a>                <span class="at">combustion =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)),</span>
<span id="cb7-7"><a href=""></a>  <span class="at">output =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>),</span>
<span id="cb7-8"><a href=""></a>  <span class="at">group  =</span> <span class="fu">data.frame</span>(<span class="at">group =</span> <span class="st">"FUEL"</span>,</span>
<span id="cb7-9"><a href=""></a>                      <span class="at">desc =</span> <span class="st">"Boiler fuel"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>),</span>
<span id="cb7-10"><a href=""></a>  <span class="at">geff   =</span> <span class="fu">data.frame</span>(<span class="at">group =</span> <span class="st">"FUEL"</span>,</span>
<span id="cb7-11"><a href=""></a>                      <span class="at">ginp2use =</span> <span class="fl">0.38</span>),</span>
<span id="cb7-12"><a href=""></a>  <span class="at">ceff   =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="fu">c</span>(<span class="st">"COA"</span>, <span class="st">"BIO"</span>),</span>
<span id="cb7-13"><a href=""></a>                      <span class="at">cinp2ginp =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>),</span>
<span id="cb7-14"><a href=""></a>                      <span class="at">share.up  =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.30</span>)),</span>
<span id="cb7-15"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span>, <span class="at">olife =</span> <span class="dv">30</span>L</span>
<span id="cb7-16"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-12-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="grouped-input-what-the-picture-tells-you" class="slide level2 smaller">
<h2>Grouped input: what the picture tells you</h2>
<div class="columns">
<div class="column" style="width:52%;">
<ul>
<li>The <strong><code>ginp</code> column appears</strong> — it is absent for a single-fuel technology.</li>
<li><code>FUEL</code> is a node: both fuels flow into it, and <em>it</em> carries the efficiency (<code>ginp2use: 0.38</code>).</li>
<li><code>[0, 0.30]</code> next to BIO is the <strong>share bound</strong>: biomass may supply at most 30 % of the boiler’s fuel.</li>
<li><code>[0, 1]</code> next to COA: coal may supply all of it.</li>
</ul>
<p>. . .</p>
<p><strong>Why group at all?</strong> Without a group each fuel would need its own efficiency and could not be constrained <em>relative to the other</em>. Shares are the point.</p>
</div><div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-13-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="multiple-outputs-chp" class="slide level2 smaller">
<h2>Multiple outputs: CHP</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p>One activity, two products. <code>cact2cout</code> sets how much of each comes out per unit of activity.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>ECHP <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb8-2"><a href=""></a>  <span class="at">name   =</span> <span class="st">"ECHP"</span>,</span>
<span id="cb8-3"><a href=""></a>  <span class="at">desc   =</span> <span class="st">"Gas CHP: power and heat"</span>,</span>
<span id="cb8-4"><a href=""></a>  <span class="at">input  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"GAS"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>,</span>
<span id="cb8-5"><a href=""></a>                <span class="at">combustion =</span> <span class="dv">1</span>),</span>
<span id="cb8-6"><a href=""></a>  <span class="at">output =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="fu">c</span>(<span class="st">"ELC"</span>, <span class="st">"HEA"</span>),</span>
<span id="cb8-7"><a href=""></a>                <span class="at">unit =</span> <span class="fu">c</span>(<span class="st">"PJ"</span>, <span class="st">"PJ"</span>)),</span>
<span id="cb8-8"><a href=""></a>  <span class="at">ceff   =</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-9"><a href=""></a>    <span class="at">comm      =</span> <span class="fu">c</span>(<span class="st">"ELC"</span>, <span class="st">"HEA"</span>),</span>
<span id="cb8-10"><a href=""></a>    <span class="at">cact2cout =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">1.2</span>)      <span class="co"># heat/power ratio</span></span>
<span id="cb8-11"><a href=""></a>  ),</span>
<span id="cb8-12"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span>, <span class="at">olife =</span> <span class="dv">25</span>L</span>
<span id="cb8-13"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Fixing both makes the ratio rigid; bound them instead for a flexible CHP.</p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-15-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="auxiliary-commodities" class="slide level2 smaller">
<h2>Auxiliary commodities</h2>
<p><strong>Main</strong> commodities (red) are tied to capacity and activity. <strong>Auxiliary</strong> commodities (blue) are anything else the process consumes or emits — land, water, steel, labour, pollutants.</p>
<p>They are declared in <code>aux</code>, and linked in <code>aeff</code> by choosing <em>which</em> quantity they scale with:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coefficient</th>
<th>Scales with</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cinp2ainp</code>, <code>cinp2aout</code></td>
<td>main commodity <strong>input</strong></td>
</tr>
<tr class="even">
<td><code>cout2ainp</code>, <code>cout2aout</code></td>
<td>main commodity <strong>output</strong></td>
</tr>
<tr class="odd">
<td><code>act2ainp</code>, <code>act2aout</code></td>
<td><strong>activity</strong></td>
</tr>
<tr class="even">
<td><code>cap2ainp</code>, <code>cap2aout</code></td>
<td><strong>installed capacity</strong></td>
</tr>
<tr class="odd">
<td><code>ncap2ainp</code>, <code>ncap2aout</code></td>
<td><strong>new capacity</strong> (built this year)</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><code>…ainp</code> = the process <em>consumes</em> it, <code>…aout</code> = the process <em>produces</em> it.</p>
</div>
</section>
<section id="aux-linked-to-capacity-activity-new-capacity" class="slide level2 smaller">
<h2>Aux linked to capacity, activity, new capacity</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>ENUC <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb9-2"><a href=""></a>  <span class="at">name   =</span> <span class="st">"ENUC"</span>,</span>
<span id="cb9-3"><a href=""></a>  <span class="at">desc   =</span> <span class="st">"Nuclear: land, water, steel"</span>,</span>
<span id="cb9-4"><a href=""></a>  <span class="at">input  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"NUC"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>),</span>
<span id="cb9-5"><a href=""></a>  <span class="at">output =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>),</span>
<span id="cb9-6"><a href=""></a>  <span class="at">aux    =</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-7"><a href=""></a>    <span class="at">acomm =</span> <span class="fu">c</span>(<span class="st">"LAND"</span>, <span class="st">"WAT"</span>, <span class="st">"STEEL"</span>),</span>
<span id="cb9-8"><a href=""></a>    <span class="at">unit  =</span> <span class="fu">c</span>(<span class="st">"km2"</span>, <span class="st">"Mm3"</span>, <span class="st">"kt"</span>)),</span>
<span id="cb9-9"><a href=""></a>  <span class="at">aeff   =</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-10"><a href=""></a>    <span class="at">acomm     =</span> <span class="fu">c</span>(<span class="st">"LAND"</span>, <span class="st">"WAT"</span>, <span class="st">"STEEL"</span>),</span>
<span id="cb9-11"><a href=""></a>    <span class="at">cap2ainp  =</span> <span class="fu">c</span>(<span class="fl">0.5</span>,  <span class="cn">NA</span>,   <span class="cn">NA</span>),   <span class="co"># per GW held</span></span>
<span id="cb9-12"><a href=""></a>    <span class="at">act2ainp  =</span> <span class="fu">c</span>(<span class="cn">NA</span>,   <span class="fl">0.02</span>, <span class="cn">NA</span>),   <span class="co"># per PJ made</span></span>
<span id="cb9-13"><a href=""></a>    <span class="at">ncap2ainp =</span> <span class="fu">c</span>(<span class="cn">NA</span>,   <span class="cn">NA</span>,   <span class="dv">40</span>)    <span class="co"># per GW built</span></span>
<span id="cb9-14"><a href=""></a>  ),</span>
<span id="cb9-15"><a href=""></a>  <span class="at">ceff =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"NUC"</span>, <span class="at">cinp2use =</span> <span class="fl">0.35</span>),</span>
<span id="cb9-16"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span>, <span class="at">olife =</span> <span class="dv">50</span>L</span>
<span id="cb9-17"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-17-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="why-the-distinction-matters" class="slide level2 smaller">
<h2>Why the distinction matters</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>Three physically different things, and the diagram labels each one:</p>
<ul>
<li><strong><code>cap2ainp: 0.50</code></strong> — land is occupied for as long as the plant <em>stands</em>, whether or not it runs.</li>
<li><strong><code>act2ainp: 0.02</code></strong> — cooling water is drawn only when it <em>generates</em>.</li>
<li><strong><code>ncap2ainp: 40.00</code></strong> — steel is consumed <strong>once</strong>, in the year the plant is <em>built</em>.</li>
</ul>
<p>. . .</p>
<p>Pick the wrong one and the model is quietly wrong: steel on <code>cap2ainp</code> would re-buy the whole plant every year.</p>
</div><div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-18-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="aux-as-emissions" class="slide level2 smaller">
<h2>Aux as emissions</h2>
<div class="columns">
<div class="column" style="width:58%;">
<p>Pollutants that depend on the <em>plant</em>, not only the fuel, are auxiliary <strong>outputs</strong> scaled by fuel input:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>ECOA_E <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb10-2"><a href=""></a>  <span class="at">name   =</span> <span class="st">"ECOA_E"</span>,</span>
<span id="cb10-3"><a href=""></a>  <span class="at">desc   =</span> <span class="st">"Coal plant with NOx and SOx"</span>,</span>
<span id="cb10-4"><a href=""></a>  <span class="at">input  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"COA"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>,</span>
<span id="cb10-5"><a href=""></a>                <span class="at">combustion =</span> <span class="dv">1</span>),</span>
<span id="cb10-6"><a href=""></a>  <span class="at">output =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>),</span>
<span id="cb10-7"><a href=""></a>  <span class="at">aux    =</span> <span class="fu">data.frame</span>(<span class="at">acomm =</span> <span class="fu">c</span>(<span class="st">"NOX"</span>, <span class="st">"SOX"</span>),</span>
<span id="cb10-8"><a href=""></a>                      <span class="at">unit  =</span> <span class="fu">c</span>(<span class="st">"kt"</span>, <span class="st">"kt"</span>)),</span>
<span id="cb10-9"><a href=""></a>  <span class="at">aeff   =</span> <span class="fu">data.frame</span>(<span class="at">acomm =</span> <span class="fu">c</span>(<span class="st">"NOX"</span>, <span class="st">"SOX"</span>),</span>
<span id="cb10-10"><a href=""></a>                      <span class="at">comm  =</span> <span class="st">"COA"</span>,</span>
<span id="cb10-11"><a href=""></a>                      <span class="at">cinp2aout =</span> <span class="fu">c</span>(<span class="fl">0.30</span>, <span class="fl">0.45</span>)),</span>
<span id="cb10-12"><a href=""></a>  <span class="at">ceff =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"COA"</span>, <span class="at">cinp2use =</span> <span class="fl">0.40</span>),</span>
<span id="cb10-13"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span>, <span class="at">olife =</span> <span class="dv">30</span>L</span>
<span id="cb10-14"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Contrast with CO<sub>2</sub>, which sits on the <strong>commodity</strong> — every burner inherits it.</p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-20-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="newstorage-moving-energy-in-time" class="slide level2 smaller">
<h2><code>newStorage()</code> — moving energy in time</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>STG_BTR <span class="ot">&lt;-</span> <span class="fu">newStorage</span>(</span>
<span id="cb11-2"><a href=""></a>  <span class="at">name      =</span> <span class="st">"STG_BTR"</span>,</span>
<span id="cb11-3"><a href=""></a>  <span class="at">desc      =</span> <span class="st">"4-hour battery"</span>,</span>
<span id="cb11-4"><a href=""></a>  <span class="at">commodity =</span> <span class="st">"ELC"</span>,</span>
<span id="cb11-5"><a href=""></a>  <span class="at">seff      =</span> <span class="fu">data.frame</span>(<span class="at">inpeff =</span> <span class="fl">0.92</span>,</span>
<span id="cb11-6"><a href=""></a>                         <span class="at">outeff =</span> <span class="fl">0.92</span>),</span>
<span id="cb11-7"><a href=""></a>  <span class="at">cap2stg   =</span> <span class="dv">4</span>,          <span class="co"># GWh per GW</span></span>
<span id="cb11-8"><a href=""></a>  <span class="at">invcost   =</span> <span class="fu">list</span>(<span class="at">invcost =</span> <span class="dv">800</span>),</span>
<span id="cb11-9"><a href=""></a>  <span class="at">olife     =</span> <span class="dv">15</span>L</span>
<span id="cb11-10"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>seff</code> — charge / discharge efficiency, and <code>stgeff</code> for standing losses.</li>
<li><code>cap2stg</code> — how many hours of storage one unit of capacity buys.</li>
<li>Only meaningful with <strong>sub-annual slices</strong> — see the <em>Time and storage</em> chapter.</li>
</ul>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-22-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="newtrade-moving-energy-in-space" class="slide level2 smaller">
<h2><code>newTrade()</code> — moving energy in space</h2>
<div class="columns">
<div class="column" style="width:58%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a>TBD_ELC <span class="ot">&lt;-</span> <span class="fu">newTrade</span>(</span>
<span id="cb12-2"><a href=""></a>  <span class="at">name      =</span> <span class="st">"TBD_ELC"</span>,</span>
<span id="cb12-3"><a href=""></a>  <span class="at">desc      =</span> <span class="st">"Interregional power line"</span>,</span>
<span id="cb12-4"><a href=""></a>  <span class="at">commodity =</span> <span class="st">"ELC"</span>,</span>
<span id="cb12-5"><a href=""></a>  <span class="at">routes    =</span> <span class="fu">data.frame</span>(          <span class="co"># which links exist</span></span>
<span id="cb12-6"><a href=""></a>    <span class="at">src =</span> <span class="fu">c</span>(<span class="st">"R1"</span>, <span class="st">"R2"</span>),</span>
<span id="cb12-7"><a href=""></a>    <span class="at">dst =</span> <span class="fu">c</span>(<span class="st">"R2"</span>, <span class="st">"R1"</span>)</span>
<span id="cb12-8"><a href=""></a>  ),</span>
<span id="cb12-9"><a href=""></a>  <span class="at">trade     =</span> <span class="fu">data.frame</span>(          <span class="co"># their parameters</span></span>
<span id="cb12-10"><a href=""></a>    <span class="at">src  =</span> <span class="fu">c</span>(<span class="st">"R1"</span>, <span class="st">"R2"</span>),</span>
<span id="cb12-11"><a href=""></a>    <span class="at">dst  =</span> <span class="fu">c</span>(<span class="st">"R2"</span>, <span class="st">"R1"</span>),</span>
<span id="cb12-12"><a href=""></a>    <span class="at">teff =</span> <span class="fl">0.95</span>                    <span class="co"># line losses</span></span>
<span id="cb12-13"><a href=""></a>  ),</span>
<span id="cb12-14"><a href=""></a>  <span class="at">invcost =</span> <span class="fu">list</span>(<span class="at">invcost =</span> <span class="dv">1500</span>)</span>
<span id="cb12-15"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Two slots, two jobs: <strong><code>routes</code></strong> declares the links, <strong><code>trade</code></strong> parameterises them. One is not derived from the other — a route with no parameters is unconstrained, and parameters for an undeclared route are ignored.</p>
<p>Trade is <strong>directional</strong>, so a bidirectional line is <em>two</em> rows in each. Note it has no <code>region</code> — the regions are <code>src</code> and <code>dst</code>.</p>
</div><div class="column" style="width:42%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-24-1.png" width="676"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="newrepository-the-bag" class="slide level2 smaller">
<h2><code>newRepository()</code> — the bag</h2>
<p>A repository is an ordered collection of objects. It has no behaviour of its own; it exists so a model can be assembled from named parts.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>repo <span class="ot">&lt;-</span> <span class="fu">newRepository</span>(</span>
<span id="cb13-2"><a href=""></a>  <span class="at">name =</span> <span class="st">"power"</span>,</span>
<span id="cb13-3"><a href=""></a>  COA, SUP_COA, ECOA, ECOFIRE, ECHP, ENUC, STG_BTR, DEM_ELC</span>
<span id="cb13-4"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>class: repository </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>objects: 8 </code></pre>
</div>
</div>
<ul>
<li>Repositories can be <strong>combined</strong> and passed around, so a scenario is “base repo + a few replacements”.</li>
<li><code>add()</code> / <code>update()</code> return a <em>modified copy</em> — nothing is mutated in place.</li>
</ul>
</section>
<section id="newhorizon-and-newmodel" class="slide level2 smaller">
<h2><code>newHorizon()</code> and <code>newModel()</code></h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a>mod <span class="ot">&lt;-</span> <span class="fu">newModel</span>(</span>
<span id="cb16-2"><a href=""></a>  <span class="at">name     =</span> <span class="st">"POWER"</span>,</span>
<span id="cb16-3"><a href=""></a>  <span class="at">desc     =</span> <span class="st">"A small power system"</span>,</span>
<span id="cb16-4"><a href=""></a>  <span class="at">data     =</span> repo,</span>
<span id="cb16-5"><a href=""></a>  <span class="at">region   =</span> <span class="st">"R1"</span>,</span>
<span id="cb16-6"><a href=""></a>  <span class="at">discount =</span> <span class="fl">0.05</span>,</span>
<span id="cb16-7"><a href=""></a>  <span class="at">horizon  =</span> <span class="fu">newHorizon</span>(</span>
<span id="cb16-8"><a href=""></a>    <span class="at">period     =</span> <span class="dv">2025</span><span class="sc">:</span><span class="dv">2050</span>,</span>
<span id="cb16-9"><a href=""></a>    <span class="at">intervals  =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>), <span class="co"># years per period</span></span>
<span id="cb16-10"><a href=""></a>    <span class="at">mid_is_end =</span> <span class="cn">TRUE</span></span>
<span id="cb16-11"><a href=""></a>  )</span>
<span id="cb16-12"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong><code>region</code></strong> — the model’s regions; objects with no <code>region</code> apply to all.</li>
<li><strong><code>horizon</code></strong> — milestone years. Periods grow, so the near term is resolved finely and the far term cheaply.</li>
<li>The model is still just a <strong>description</strong>. <code>interpolate_model()</code> expands it over regions × years × slices; <code>solve_scenario()</code> solves it.</li>
</ul>
</section>
<section id="putting-it-together" class="slide level2 smaller">
<h2>Putting it together</h2>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Makes</th>
<th style="text-align: center;">Drawn?</th>
<th>Key arguments</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>newCommodity()</code></td>
<td>a flow</td>
<td style="text-align: center;">—</td>
<td><code>unit</code>, <code>timeframe</code>, <code>emis</code></td>
</tr>
<tr class="even">
<td><code>newSupply()</code></td>
<td>a resource</td>
<td style="text-align: center;">✔</td>
<td><code>supply</code>: <code>cost</code>, <code>ava.up</code></td>
</tr>
<tr class="odd">
<td><code>newDemand()</code></td>
<td>an obligation</td>
<td style="text-align: center;">✔</td>
<td><code>demand</code></td>
</tr>
<tr class="even">
<td><code>newImport()</code> / <code>newExport()</code></td>
<td>rest-of-world flow</td>
<td style="text-align: center;">✔</td>
<td><code>price</code>, <code>imp.up</code> / <code>exp.up</code></td>
</tr>
<tr class="odd">
<td><code>newTechnology()</code></td>
<td>a converter</td>
<td style="text-align: center;">✔</td>
<td><code>input</code>, <code>output</code>, <code>ceff</code>, <code>aeff</code>, <code>invcost</code></td>
</tr>
<tr class="even">
<td><code>newStorage()</code></td>
<td>time shifting</td>
<td style="text-align: center;">✔</td>
<td><code>seff</code>, <code>cap2stg</code></td>
</tr>
<tr class="odd">
<td><code>newTrade()</code></td>
<td>space shifting</td>
<td style="text-align: center;">✔</td>
<td><code>routes</code>, then <code>trade</code>: <code>src</code>, <code>dst</code>, <code>teff</code></td>
</tr>
<tr class="even">
<td><code>newRepository()</code></td>
<td>a bag of objects</td>
<td style="text-align: center;">—</td>
<td><code>name</code>, <code>...</code></td>
</tr>
<tr class="odd">
<td><code>newModel()</code></td>
<td>the description</td>
<td style="text-align: center;">—</td>
<td><code>data</code>, <code>region</code>, <code>horizon</code></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>When in doubt, <code>draw()</code> it.</strong> If the picture is not the system you meant, the model is not either.</p>
</div>
</section></section>
<section>
<section id="where-objects-live-time" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>2 · Where objects live: time</h1>

</section>
<section id="calendars-the-time-structure" class="slide level2 smaller">
<h2>Calendars: the time structure</h2>
<p>A <strong>calendar</strong> declares the sub-annual structure every flow is balanced on. It is a set of nested <em>timeframes</em>, each split into <em>slices</em> carrying a share of the year.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="fu">make_timetable</span>(<span class="fu">list</span>(<span class="at">SEASON  =</span> <span class="fu">c</span>(<span class="st">"WI"</span>, <span class="st">"SP"</span>, <span class="st">"SU"</span>, <span class="st">"FA"</span>),</span>
<span id="cb17-2"><a href=""></a>                    <span class="at">DAYNITE =</span> <span class="fu">c</span>(<span class="st">"D"</span>, <span class="st">"N"</span>)))  <span class="sc">|&gt;</span> <span class="fu">head</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   ANNUAL SEASON DAYNITE  slice share weight
   &lt;char&gt; &lt;char&gt;  &lt;char&gt; &lt;char&gt; &lt;num&gt;  &lt;num&gt;
1: ANNUAL     FA       D   FA_D 0.125      1
2: ANNUAL     FA       N   FA_N 0.125      1
3: ANNUAL     SP       D   SP_D 0.125      1
4: ANNUAL     SP       N   SP_N 0.125      1</code></pre>
</div>
</div>
<ul>
<li>Nesting is the grammar: <code>SEASON</code> above <code>DAYNITE</code> gives 8 slices.</li>
<li>Every parent timeframe currently needs the <strong>same number of children</strong> — a regular tree, not a ragged one.</li>
<li><code>newCalendar(name, timetable, year_fraction)</code> turns a timetable into an object.</li>
</ul>
</section>
<section id="ready-made-calendars" class="slide level2 smaller">
<h2>Ready-made calendars</h2>
<p>Eight ship with the package — the fastest way to change a model’s time resolution is to swap one in.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="fu">names</span>(calendars)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "season_dn"                      "d365"                          
[3] "utopia_annual"                  "utopia_seasons"                
[5] "utopia_s4h24"                   "utopia_m12h24"                 
[7] "d365_h24"                       "d365_h24_subset_1day_per_month"</code></pre>
</div>
</div>
<div class="columns">
<div class="column" style="width:46%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-30-1.png" width="598"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:54%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-31-1.png" width="702"></p>
</figure>
</div>
</div>
</div>
</div></div>
<p>Each rectangle is one slice, sized by its share of the year. <code>ANNUAL</code> sits on top; finer timeframes stack below.</p>
</section>
<section id="sampled-vs-full-calendars" class="slide level2 smaller">
<h2>Sampled vs full calendars</h2>
<div class="columns">
<div class="column" style="width:52%;">
<p>A <strong>sampled</strong> calendar keeps a representative subset of slices and declares what fraction of the year it covers:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a>sub  <span class="ot">&lt;-</span> calendars<span class="sc">$</span>d365_h24_subset_1day_per_month</span>
<span id="cb21-2"><a href=""></a>full <span class="ot">&lt;-</span> calendars<span class="sc">$</span>d365_h24</span>
<span id="cb21-3"><a href=""></a></span>
<span id="cb21-4"><a href=""></a><span class="fu">data.frame</span>(<span class="at">slices        =</span> <span class="fu">c</span>(<span class="fu">nrow</span>(sub<span class="sc">@</span>timetable), <span class="fu">nrow</span>(full<span class="sc">@</span>timetable)),</span>
<span id="cb21-5"><a href=""></a>           <span class="at">year_fraction =</span> <span class="fu">round</span>(<span class="fu">c</span>(sub<span class="sc">@</span>year_fraction, full<span class="sc">@</span>year_fraction), <span class="dv">4</span>),</span>
<span id="cb21-6"><a href=""></a>           <span class="at">row.names     =</span> <span class="fu">c</span>(<span class="st">"sampled"</span>, <span class="st">"full"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        slices year_fraction
sampled    288        0.0329
full      8760        1.0000</code></pre>
</div>
</div>
<p>One day per month at hourly resolution — <strong>288 slices instead of 8760</strong>, about 3.3 % of the year.</p>
<p><code>year_fraction</code> is what keeps annual quantities honest when only part of the year is modelled.</p>
</div><div class="column" style="width:48%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-33-1.png" width="650"></p>
</figure>
</div>
</div>
</div>
<p>Passing <code>reference =</code> lays out the <strong>full</strong> structure and fills only the slices the sampled calendar declares.</p>
</div></div>
</section>
<section id="aggregating-time-in-results" class="slide level2 smaller">
<h2>Aggregating time in results</h2>
<p>Sampling reduces what is <em>solved</em>. Aggregation changes what you <em>read back</em> — <code>getData()</code> takes a <code>timeframe</code> argument:</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><code>timeframe =</code></th>
<th>Returns</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>"lowest"</code> <em>(default)</em></td>
<td>flows summed up to the coarsest level, normally <code>ANNUAL</code></td>
</tr>
<tr class="even">
<td><code>"highest"</code></td>
<td>native resolution, as stored</td>
</tr>
<tr class="odd">
<td><code>"all"</code></td>
<td>every level, stacked</td>
</tr>
<tr class="even">
<td><code>"SEASON"</code>, <code>"YDAY"</code>, …</td>
<td>one named calendar level</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>State variables (a storage level, say) are <strong>returned unchanged</strong> — summing a level over slices is meaningless, and the package knows the difference.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Roadmap <span class="badge planned">planned</span></strong></p>
</div>
<div class="callout-content">
<p>Nested timeframes and slice aggregation/disaggregation as a first-class operation move to the <strong>timescales</strong> package — the temporal companion to <code>geoscales</code>. Today energyRt’s calendar machinery is self-contained.</p>
</div>
</div>
</div>
</div>
</section>
<section id="horizons-the-years" class="slide level2 smaller">
<h2>Horizons: the years</h2>
<div class="columns">
<div class="column" style="width:55%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a>h <span class="ot">&lt;-</span> <span class="fu">newHorizon</span>(<span class="at">period    =</span> <span class="dv">2025</span><span class="sc">:</span><span class="dv">2050</span>,</span>
<span id="cb23-2"><a href=""></a>                <span class="at">intervals =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb23-3"><a href=""></a>h<span class="sc">@</span>intervals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   start   mid   end
   &lt;num&gt; &lt;num&gt; &lt;num&gt;
1:  2025  2025  2025
2:  2026  2028  2030
3:  2031  2033  2035
4:  2036  2038  2040
5:  2041  2043  2045
6:  2046  2048  2050</code></pre>
</div>
</div>
<ul>
<li><strong><code>period</code></strong> — the full span of years.</li>
<li><strong><code>intervals</code></strong> — either lengths (as here) or a <code>data.frame</code> with <code>start</code>, <code>mid</code>, <code>end</code>.</li>
<li>The first interval is forced to a single <strong>base year</strong> (<code>force_BY_interval_to_1_year = TRUE</code>).</li>
<li>The <strong>mid</strong> is the milestone year the solver actually optimises.</li>
</ul>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-35-1.png" width="650"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="where-the-milestone-year-sits" class="slide level2 smaller">
<h2>Where the milestone year sits</h2>
<p>The same intervals, three placements of the mid-year — the dashed line:</p>

<img data-src="builders_files/figure-revealjs/unnamed-chunk-36-1.png" width="1690" class="r-stretch"><div class="fragment">
<p>It matters because <strong>costs and demands are evaluated at the mid</strong>. <code>mid_is_end</code> puts the decision at the end of each period — the convention used in the models we build here. Choose once, and keep it consistent across scenarios you compare.</p>
</div>
</section>
<section id="ready-made-horizons" class="slide level2 smaller">
<h2>Ready-made horizons</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a><span class="fu">names</span>(horizons)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Y2020_2060_by_5"  "Y2020_2060_by_10" "Y2020"            "Y2030"           
[5] "Y2040"            "Y2050"            "Y2060"            "Y2070"           </code></pre>
</div>
</div>

<img data-src="builders_files/figure-revealjs/unnamed-chunk-38-1.png" width="1430" class="r-stretch"><p>Single-year horizons (<code>Y2030</code>, <code>Y2050</code>, …) are useful for a fast structural check: build the model, solve one year, confirm it is feasible before paying for the full run.</p>
</section></section>
<section>
<section id="where-objects-live-space" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>3 · Where objects live: space</h1>

</section>
<section id="regions" class="slide level2 smaller">
<h2>Regions</h2>
<p>There is <strong>no <code>newRegion()</code></strong>. Regions are a flat character vector declared on the model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="fu">newModel</span>(<span class="st">"POWER"</span>, <span class="at">data =</span> repo, <span class="at">region =</span> <span class="fu">c</span>(<span class="st">"R1"</span>, <span class="st">"R2"</span>, <span class="st">"R3"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Objects carry an optional <code>region</code> slot; <strong>leaving it empty means every region</strong>.</li>
<li><code>trade</code> is the exception — it has no <code>region</code>, only <code>src</code> and <code>dst</code>.</li>
<li><code>get_region(obj)</code> walks any object and reports the regions it refers to. It is deliberately schema-agnostic, so it keeps working as region information is added to classes that do not carry it yet.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="fu">get_region</span>(TBD_ELC)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R1" "R2"</code></pre>
</div>
</div>
</section>
<section id="geoscales-nesting-regions" class="slide level2 smaller">
<h2>Geoscales: nesting regions</h2>
<p>A <strong>geoscale</strong> (from the companion <code>geoscales</code> package) describes how regions nest into coarser levels, their weights, and optionally their geometry.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a>gs <span class="ot">&lt;-</span> <span class="fu">utopia_geoscale</span>()   <span class="co"># UTOPIA's 11 regions: nation &gt; zone &gt; region</span></span>
<span id="cb30-2"><a href=""></a><span class="fu">class</span>(gs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "geoscales::Geoscale" "S7_object"          </code></pre>
</div>
</div>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The one sentence to remember</strong></p>
</div>
<div class="callout-content">
<p>A geoscale is used for <strong>plotting, reporting and subsetting only</strong>. Attaching one <em>never changes the optimisation model</em>. The extra members stay inert until some commodity names a coarser level.</p>
</div>
</div>
</div>
<ul>
<li><code>setGeoscale()</code> / <code>getGeoscale()</code> on a <code>config</code>, <code>model</code> or <code>scenario</code>.</li>
<li><code>getData(..., geolevel = )</code> aggregates results up the hierarchy — <code>"finest"</code>, <code>"coarsest"</code>, <code>"all"</code>, or a named level.</li>
<li><code>plot_map()</code> draws results on the geometry (needs <code>sf</code>).</li>
<li>Inter-regional <strong>flows</strong> are returned unchanged by <code>geolevel</code> aggregation — summing a flow across regions would double-count it.</li>
</ul>
</section></section>
<section>
<section id="commodities-in-depth" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>4 · Commodities in depth</h1>

</section>
<section id="nine-slots-and-what-each-decides" class="slide level2 smaller">
<h2>Nine slots, and what each decides</h2>
<div class="small-table">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Slot</th>
<th>Decides</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>name</code>, <code>desc</code></td>
<td>identity</td>
</tr>
<tr class="even">
<td><code>limtype</code></td>
<td>how the balance closes: <code>LO</code> (default, excess allowed), <code>UP</code>, <code>FX</code></td>
</tr>
<tr class="odd">
<td><code>timeframe</code></td>
<td><strong>where it balances in time</strong> — finest level in the model by default</td>
</tr>
<tr class="even">
<td><code>geolevel</code></td>
<td><strong>where it balances in space</strong> <span class="badge limited">GLPK / GAMS only</span></td>
</tr>
<tr class="odd">
<td><code>unit</code></td>
<td>the commodity’s main unit</td>
</tr>
<tr class="even">
<td><code>emis</code></td>
<td>emission factors carried by the fuel</td>
</tr>
<tr class="odd">
<td><code>agg</code></td>
<td>weights aggregating several commodities into this one</td>
</tr>
<tr class="even">
<td><code>misc</code></td>
<td>free-form; never read by the model</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>The commodity is deliberately <strong>lean</strong>: it is a label with balancing rules. All the engineering lives on the processes that consume and produce it.</p>
</div>
</section>
<section id="where-a-commodity-lives" class="slide level2 smaller">
<h2>Where a commodity lives</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>In time — <code>timeframe</code></strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a><span class="fu">newCommodity</span>(<span class="st">"ELC"</span>, <span class="at">timeframe =</span> <span class="st">"HOUR"</span>)</span>
<span id="cb32-2"><a href=""></a><span class="fu">newCommodity</span>(<span class="st">"COA"</span>, <span class="at">timeframe =</span> <span class="st">"ANNUAL"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Electricity must balance every hour; coal only has to balance over the year. Setting <code>ANNUAL</code> on a carrier that genuinely needs hourly matching is one of the easiest ways to build a model that is quietly too optimistic.</p>
</div><div class="column" style="width:50%;">
<p><strong>In space — <code>geolevel</code></strong> <span class="badge exp">experimental</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a><span class="fu">newCommodity</span>(<span class="st">"STEEL"</span>, <span class="at">geolevel =</span> <span class="st">"nation"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Naming a coarser level asserts <strong>free, unlimited transport within that level</strong>. That suits an integrated goods market; it is wrong for a network-constrained carrier such as electricity.</p>
<p>Requires a geoscale on the model config.</p>
</div></div>
</section>
<section id="carbon-and-other-emissions" class="slide level2 smaller">
<h2>Carbon and other emissions</h2>
<div class="columns">
<div class="column" style="width:54%;">
<p>Emission factors ride on the <strong>fuel</strong>, so every technology burning it inherits them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a>COA2 <span class="ot">&lt;-</span> <span class="fu">newCommodity</span>(<span class="st">"COA"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>,</span>
<span id="cb34-2"><a href=""></a>  <span class="at">emis =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"CO2"</span>, <span class="at">unit =</span> <span class="st">"kt/PJ"</span>, <span class="at">emis =</span> <span class="dv">95</span>))</span>
<span id="cb34-3"><a href=""></a>GAS2 <span class="ot">&lt;-</span> <span class="fu">newCommodity</span>(<span class="st">"GAS"</span>, <span class="at">unit =</span> <span class="st">"PJ"</span>,</span>
<span id="cb34-4"><a href=""></a>  <span class="at">emis =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"CO2"</span>, <span class="at">unit =</span> <span class="st">"kt/PJ"</span>, <span class="at">emis =</span> <span class="dv">56</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The factor only fires where the consuming technology declares <code>combustion = 1</code> on that input.</p>
<p>There is <strong>no separate carbon-content slot</strong> — <code>@emis</code> is the single mechanism, and it generalises to any emitted species.</p>
</div><div class="column" style="width:46%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-45-1.png" width="624"></p>
</figure>
</div>
</div>
</div>
</div></div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Roadmap <span class="badge planned">planned</span></strong></p>
</div>
<div class="callout-content">
<p>Physical properties — mass, volume, heating value — are <strong>not</strong> slots today, and <code>@misc</code> is the documented place to park them meanwhile. Adding them as first-class, unit-aware slots is a candidate for a future release.</p>
</div>
</div>
</div>
</section>
<section id="plant-specific-pollutants-are-different" class="slide level2 smaller">
<h2>Plant-specific pollutants are different</h2>
<p>A useful contrast, since both end up as “emissions”:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Where it lives</th>
<th>Mechanism</th>
<th>Use when</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Commodity</strong> <code>@emis</code></td>
<td>factor per unit of fuel burned</td>
<td>CO<sub>2</sub> — depends only on the fuel’s carbon</td>
</tr>
<tr class="even">
<td><strong>Technology</strong> <code>aeff</code> <code>cinp2aout</code></td>
<td>auxiliary <em>output</em> scaled by input</td>
<td>NO<sub>x</sub>, SO<sub>x</sub> — depend on the burner, not just the fuel</td>
</tr>
</tbody>
</table>
<p>Two plants burning identical coal emit identical CO<sub>2</sub> and quite different NO<sub>x</sub>. That is the whole distinction.</p>
</section></section>
<section>
<section id="vintages-and-clusters" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>5 · Vintages and clusters</h1>

</section>
<section id="one-technology-many-variants" class="slide level2 smaller">
<h2>One technology, many variants</h2>
<p>Real technologies are not one thing. A wind fleet has <strong>resource grades</strong> that differ in cost and yield, and <strong>build years</strong> that differ in efficiency and lifetime. energyRt expresses both on a <em>single</em> object:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Dimension</th>
<th>Slot</th>
<th>Means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>vintage</strong></td>
<td><code>@vintage</code></td>
<td>when it was built — investment window and operational life</td>
</tr>
<tr class="even">
<td><strong>cluster</strong></td>
<td><code>@cluster</code></td>
<td>which grade or variant it is — resource quality, siting class</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><code>@vintage</code> <strong>replaces</strong> the older <code>start</code> / <code>end</code> / <code>olife</code> slots: one row per (<code>vintage</code>, <code>region</code>, <code>cluster</code>) giving that variant’s window and life. A single row with <code>vintage = NA</code> is an ordinary un-vintaged technology.</p>
</div>
</section>
<section id="declaring-vintages" class="slide level2 smaller">
<h2>Declaring vintages</h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>The short form is usually enough — <code>start</code> and <code>end</code> <strong>default to the vintage year</strong>, so naming the years defines properly windowed vintages:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a>EWIN <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb35-2"><a href=""></a>  <span class="at">name    =</span> <span class="st">"EWIN"</span>,</span>
<span id="cb35-3"><a href=""></a>  <span class="at">input   =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"WIN"</span>),</span>
<span id="cb35-4"><a href=""></a>  <span class="at">output  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>),</span>
<span id="cb35-5"><a href=""></a>  <span class="at">ceff    =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"WIN"</span>, <span class="at">cinp2use =</span> <span class="dv">1</span>),</span>
<span id="cb35-6"><a href=""></a>  <span class="at">vintage =</span> <span class="fu">c</span>(<span class="st">"2025"</span>, <span class="st">"2040"</span>),</span>
<span id="cb35-7"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span></span>
<span id="cb35-8"><a href=""></a>)</span>
<span id="cb35-9"><a href=""></a>EWIN<span class="sc">@</span>vintage</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  vintage region cluster start end olife
1    2025   &lt;NA&gt;    &lt;NA&gt;    NA  NA    NA
2    2040   &lt;NA&gt;    &lt;NA&gt;    NA  NA    NA</code></pre>
</div>
</div>
</div><div class="column" style="width:45%;">
<p>The table form when the variants differ:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>vintage <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb37-2"><a href=""></a>  <span class="at">vintage =</span> <span class="fu">c</span>(<span class="st">"2025"</span>, <span class="st">"2040"</span>),</span>
<span id="cb37-3"><a href=""></a>  <span class="at">olife   =</span> <span class="fu">c</span>(<span class="dv">25</span>L, <span class="dv">30</span>L)      <span class="co"># newer lasts longer</span></span>
<span id="cb37-4"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Columns available: <code>vintage</code>, <code>region</code>, <code>cluster</code>, <code>start</code>, <code>end</code>, <code>olife</code>.</p>
</div></div>
</section>
<section id="declaring-clusters" class="slide level2 smaller">
<h2>Declaring clusters</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a>EWINVC <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb38-2"><a href=""></a>  <span class="at">name    =</span> <span class="st">"EWINVC"</span>,</span>
<span id="cb38-3"><a href=""></a>  <span class="at">desc    =</span> <span class="st">"Wind: two resource grades, two vintages"</span>,</span>
<span id="cb38-4"><a href=""></a>  <span class="at">input   =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"WIN"</span>),</span>
<span id="cb38-5"><a href=""></a>  <span class="at">output  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>),</span>
<span id="cb38-6"><a href=""></a>  <span class="at">ceff    =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"WIN"</span>, <span class="at">cinp2use =</span> <span class="dv">1</span>),</span>
<span id="cb38-7"><a href=""></a>  <span class="at">cluster =</span> <span class="fu">data.frame</span>(<span class="at">cluster =</span> <span class="fu">c</span>(<span class="st">"best"</span>, <span class="st">"mid"</span>),</span>
<span id="cb38-8"><a href=""></a>                       <span class="at">desc    =</span> <span class="fu">c</span>(<span class="st">"High wind sites"</span>, <span class="st">"Medium wind sites"</span>),</span>
<span id="cb38-9"><a href=""></a>                       <span class="at">order   =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>),</span>
<span id="cb38-10"><a href=""></a>  <span class="at">vintage =</span> <span class="fu">data.frame</span>(<span class="at">vintage =</span> <span class="fu">c</span>(<span class="st">"2025"</span>, <span class="st">"2040"</span>), <span class="at">olife =</span> <span class="dv">25</span>L),</span>
<span id="cb38-11"><a href=""></a>  <span class="at">invcost =</span> <span class="fu">data.frame</span>(<span class="at">cluster =</span> <span class="fu">c</span>(<span class="st">"best"</span>, <span class="st">"best"</span>, <span class="st">"mid"</span>,  <span class="st">"mid"</span>),</span>
<span id="cb38-12"><a href=""></a>                       <span class="at">vintage =</span> <span class="fu">c</span>(<span class="st">"2025"</span>, <span class="st">"2040"</span>, <span class="st">"2025"</span>, <span class="st">"2040"</span>),</span>
<span id="cb38-13"><a href=""></a>                       <span class="at">invcost =</span> <span class="fu">c</span>(<span class="dv">1400</span>,   <span class="dv">1150</span>,   <span class="dv">1600</span>,   <span class="dv">1300</span>)),</span>
<span id="cb38-14"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span></span>
<span id="cb38-15"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><strong>Nothing new was learned.</strong> Parameters vary by variant by gaining one more selector column — exactly like <code>region</code> or <code>year</code>. <code>2 × 2 = 4</code> cells, one object.</p>
</div>
</section>
<section id="draw-reads-the-whole-grid" class="slide level2 smaller">
<h2><code>draw()</code> reads the whole grid</h2>
<div class="columns">
<div class="column" style="width:42%;">
<p>Ask for one cell and you get it, with the other vintages behind it as <strong>ghosts</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a><span class="fu">draw</span>(EWINVC, <span class="at">vintage =</span> <span class="st">"2040"</span>,</span>
<span id="cb39-2"><a href=""></a>             <span class="at">cluster =</span> <span class="st">"best"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The faded stack is the <em>vintage marginal</em> through the selected cell — the cells sharing its cluster. Earlier vintages sit down-left, later ones up-right, so the depth of the stack is the technology’s history.</p>
</div><div class="column" style="width:58%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-50-1.png" width="832"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="clusters-rail-deck-or-neither" class="slide level2 smaller">
<h2>Clusters: rail, deck, or neither</h2>
<p><code>cluster_style</code> changes how the sibling grades are rendered around the selected cell.</p>
<div class="columns">
<div class="column" style="width:33%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-51-1.png" width="546"></p>
</figure>
</div>
</div>
</div>
<p><code>"rail"</code> <em>(default)</em></p>
</div><div class="column" style="width:33%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-52-1.png" width="546"></p>
</figure>
</div>
</div>
</div>
<p><code>"deck"</code></p>
</div><div class="column" style="width:33%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-53-1.png" width="546"></p>
</figure>
</div>
</div>
</div>
<p><code>"none"</code></p>
</div></div>
<p>Cosmetic, not semantic — pick whichever makes the point on your slide.</p>
</section>
<section id="seeing-every-cell-at-once" class="slide level2 smaller">
<h2>Seeing every cell at once</h2>
<p>Pass <code>"all"</code> to facet a dimension instead of selecting from it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a><span class="fu">draw</span>(EWINVC, <span class="at">vintage =</span> <span class="st">"all"</span>, <span class="at">cluster =</span> <span class="st">"all"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="builders_files/figure-revealjs/unnamed-chunk-54-1.png" width="1430" class="r-stretch"><p><code>max_facets = 24L</code> guards the obvious accident — a 4-vintage × 11-region technology asked to draw everything.</p>
</section>
<section id="from-variants-to-model-objects" class="slide level2 smaller">
<h2>From variants to model objects</h2>
<p>Variants are <strong>replicated into ordinary technologies before interpolation</strong> — the solver never sees the vintage/cluster idea, only more technologies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a>mod <span class="ot">&lt;-</span> <span class="fu">expand_variants</span>(mod)     <span class="co"># or expand_tech_variants(mod)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Names gain a suffix from <code>.variant_prefix</code>, defaulting to <code>_VIN</code> and <code>_CL</code>: <code>EWINVC</code> becomes <code>EWINVC_CLbest_VIN2025</code>, <code>EWINVC_CLmid_VIN2040</code>, and so on.</p>
<div class="fragment">
<p>Reading them back after a solve:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a><span class="fu">getVariants</span>(scen)                                   <span class="co"># which variants exist</span></span>
<span id="cb42-2"><a href=""></a><span class="fu">variantSummary</span>(scen, <span class="at">name =</span> <span class="st">"EWINVC"</span>, <span class="at">by =</span> <span class="st">"vintage"</span>)  <span class="co"># rolled up again</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The point of the design: <strong>declare once, compare by grade or by build year</strong>, without hand-maintaining a dozen near-identical technology objects.</p>
</div>
</section>
<section id="design-the-object-back-as-code" class="slide level2 smaller">
<h2><code>design()</code> — the object, back as code</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p>Useful when an object came from a dataset or a colleague and you want to see what it actually says:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a><span class="fu">design</span>(ECOA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Returns (and can write to a file) the <code>newTechnology()</code> call that recreates it.</p>
<p>Note it renders the <strong>modern <code>vintage</code> table</strong> even when the object was built with the older <code>olife =</code> argument — a quick way to migrate old code.</p>
<p><span class="badge limited">technology only</span> — no <code>design()</code> method for other classes yet.</p>
</div><div class="column" style="width:54%;">
<div class="cell">
<div class="cell-output cell-output-stdout">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode numberSource small-table number-lines code-with-copy"><code class="sourceCode"><span id="cb44-1"><a href=""></a>ECOA &lt;- newTechnology(</span>
<span id="cb44-2"><a href=""></a>  name = "ECOA",</span>
<span id="cb44-3"><a href=""></a>  desc = "Coal power plant",</span>
<span id="cb44-4"><a href=""></a>  input = data.frame(</span>
<span id="cb44-5"><a href=""></a>    comm = "COA",</span>
<span id="cb44-6"><a href=""></a>    unit = "PJ",</span>
<span id="cb44-7"><a href=""></a>    combustion = 1</span>
<span id="cb44-8"><a href=""></a>  ),</span>
<span id="cb44-9"><a href=""></a>  output = data.frame(</span>
<span id="cb44-10"><a href=""></a>    comm = "ELC",</span>
<span id="cb44-11"><a href=""></a>    unit = "PJ"</span>
<span id="cb44-12"><a href=""></a>  ),</span>
<span id="cb44-13"><a href=""></a>  ceff = data.frame(</span>
<span id="cb44-14"><a href=""></a>    comm = "COA",</span>
<span id="cb44-15"><a href=""></a>    cinp2use = 0.4</span>
<span id="cb44-16"><a href=""></a>  ),</span>
<span id="cb44-17"><a href=""></a>  fixom = data.frame(</span>
<span id="cb44-18"><a href=""></a>    fixom = 55</span>
<span id="cb44-19"><a href=""></a>  ),</span>
<span id="cb44-20"><a href=""></a>  invcost = data.frame(</span>
<span id="cb44-21"><a href=""></a>    invcost = 2000</span>
<span id="cb44-22"><a href=""></a>  ),</span>
<span id="cb44-23"><a href=""></a>  vintage = data.frame(</span>
<span id="cb44-24"><a href=""></a>    olife = 30L</span>
<span id="cb44-25"><a href=""></a>  ),</span>
<span id="cb44-26"><a href=""></a>  cap2act = 31.536</span>
<span id="cb44-27"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div></div>
</section></section>
<section>
<section id="from-description-to-numbers" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>6 · From description to numbers</h1>

</section>
<section id="what-interpolate_model-does" class="slide level2 smaller scrollable">
<h2>What <code>interpolate_model()</code> does</h2>
<p>The model object is a <em>description</em>. Interpolation compiles it into a solver-ready scenario:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a>scen <span class="ot">&lt;-</span> <span class="fu">interpolate_model</span>(mod, <span class="at">name =</span> <span class="st">"BASE"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol type="1">
<li>collect the sets — regions, years, slices, commodities, processes</li>
<li>build the <strong>maps</strong>: membership, calendar, lifespan, value and cost domains</li>
<li>extract the numeric parameters and <strong>interpolate them over years</strong></li>
<li>compute equivalent annual costs</li>
<li>compile user constraints</li>
<li>reduce the data (prune / fold / densify / trim — Part 8)</li>
<li>validate</li>
</ol>
<div class="fragment">
<p>Only step 3 is interpolation in the literal sense. Regions and slices are handled by <strong>expanding <code>NA</code> wildcards</strong> — an omitted <code>region</code> column means <em>all regions</em>, and it is expanded, not interpolated.</p>
</div>
</section>
<section id="anchors-in-series-out" class="slide level2 smaller">
<h2>Anchors in, series out</h2>
<div class="columns">
<div class="column" style="width:46%;">
<p>You supply anchor years; the pipeline fills the rest:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href=""></a>ECOA_Y <span class="ot">&lt;-</span> <span class="fu">newTechnology</span>(</span>
<span id="cb46-2"><a href=""></a>  <span class="at">name    =</span> <span class="st">"ECOA_Y"</span>,</span>
<span id="cb46-3"><a href=""></a>  <span class="at">input   =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"COA"</span>, <span class="at">combustion =</span> <span class="dv">1</span>),</span>
<span id="cb46-4"><a href=""></a>  <span class="at">output  =</span> <span class="fu">list</span>(<span class="at">comm =</span> <span class="st">"ELC"</span>),</span>
<span id="cb46-5"><a href=""></a>  <span class="at">ceff    =</span> <span class="fu">data.frame</span>(<span class="at">comm =</span> <span class="st">"COA"</span>, <span class="at">cinp2use =</span> <span class="fl">0.40</span>),</span>
<span id="cb46-6"><a href=""></a>  <span class="at">invcost =</span> <span class="fu">data.frame</span>(<span class="at">year    =</span> <span class="fu">c</span>(<span class="dv">2025</span>, <span class="dv">2040</span>, <span class="dv">2050</span>),</span>
<span id="cb46-7"><a href=""></a>                       <span class="at">invcost =</span> <span class="fu">c</span>(<span class="dv">2000</span>, <span class="dv">1800</span>, <span class="dv">1700</span>)),</span>
<span id="cb46-8"><a href=""></a>  <span class="at">cap2act =</span> <span class="fl">31.536</span>, <span class="at">olife =</span> <span class="dv">30</span>L</span>
<span id="cb46-9"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>getData()</code> returns both views — the given rows, and the interpolated series:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a><span class="fu">getData</span>(ECOA_Y, <span class="at">name =</span> <span class="st">"invcost"</span>, <span class="at">merge =</span> <span class="cn">FALSE</span>)</span>
<span id="cb47-2"><a href=""></a><span class="fu">getData</span>(ECOA_Y, <span class="at">name =</span> <span class="st">"invcost"</span>, <span class="at">merge =</span> <span class="cn">FALSE</span>,</span>
<span id="cb47-3"><a href=""></a>        <span class="at">interpolate =</span> <span class="cn">TRUE</span>, <span class="at">year =</span> <span class="dv">2025</span><span class="sc">:</span><span class="dv">2050</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div><div class="column" style="width:54%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-62-1.png" width="728"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="interpolation-rules" class="slide level2 smaller">
<h2>Interpolation rules</h2>
<p>Each parameter carries a rule, stored as a composite of three tokens:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Token</th>
<th>Alias</th>
<th>Applies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>back</code></td>
<td><code>bwd</code></td>
<td>before the first anchor — backward fill</td>
</tr>
<tr class="even">
<td><code>inter</code></td>
<td><code>mid</code></td>
<td>between anchors — linear</td>
</tr>
<tr class="odd">
<td><code>forth</code></td>
<td><code>fwd</code></td>
<td>after the last anchor — forward fill</td>
</tr>
</tbody>
</table>
<p>The default nearly everywhere is <strong><code>back.inter.forth</code></strong>: constant outside the anchors, linear between them. That is why a single value with no <code>year</code> column becomes a flat line across the whole horizon.</p>
<div class="fragment">
<p>Rules live in the <code>config@interpolation</code> table. To change them, build a modified <code>config</code> (or <code>settings</code>) and pass the object — there is <strong>no scalar <code>interpolate_model(interpolation = ...)</code> argument yet</strong> <span class="badge planned">planned</span>.</p>
</div>
</section></section>
<section>
<section id="scenarios" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>7 · Scenarios</h1>

</section>
<section id="a-scenario-is-interpolatedsolved-model-with-additions" class="slide level2 smaller">
<h2>A scenario is interpolated/solved model with additions</h2>
<p><code>interpolate_model()</code> accepts <strong>energyRt objects in <code>...</code></strong> and folds them into the model before the pipeline runs. That single mechanism is the whole scenario API:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href=""></a><span class="fu">interpolate_model</span>(mod, <span class="st">"CO2CAP"</span>,  co2_cap)                  <span class="co"># a policy constraint</span></span>
<span id="cb48-2"><a href=""></a><span class="fu">interpolate_model</span>(mod, <span class="st">"SAMPLED"</span>, cal_sampled)              <span class="co"># a sampled calendar</span></span>
<span id="cb48-3"><a href=""></a><span class="fu">interpolate_model</span>(mod, <span class="st">"SHORT"</span>,   <span class="fu">newHorizon</span>(<span class="at">period =</span> <span class="dv">2025</span><span class="sc">:</span><span class="dv">2035</span>))</span>
<span id="cb48-4"><a href=""></a><span class="fu">interpolate_model</span>(mod, <span class="st">"HIGHDEM"</span>, repo_high_demand)         <span class="co"># a whole repository</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Pass an object of class</th>
<th>It replaces / adds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>calendar</code></td>
<td>the scenario’s time structure</td>
</tr>
<tr class="even">
<td><code>horizon</code></td>
<td>the milestone years</td>
</tr>
<tr class="odd">
<td><code>config</code> / <code>settings</code></td>
<td>the whole settings block</td>
</tr>
<tr class="even">
<td><code>repository</code></td>
<td>added to the model</td>
</tr>
<tr class="odd">
<td><code>technology</code>, <code>commodity</code>, <code>constraint</code>, <code>tax</code>, …</td>
<td>bundled into a scenario-specific repository</td>
</tr>
</tbody>
</table>
<p>Anything unrecognised is <strong>warned about</strong>, not silently ignored.</p>
</section>
<section id="the-same-objects-work-at-solve-time" class="slide level2 smaller">
<h2>The same objects work at solve time</h2>
<p><code>solve_scenario()</code> / <code>solve_mod()</code> split their <code>...</code>: run-control arguments stay, everything else is routed straight to interpolation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a><span class="fu">solve_mod</span>(mod, <span class="st">"COARSE"</span>, <span class="at">solver =</span> solver_options<span class="sc">$</span>glpk,</span>
<span id="cb49-2"><a href=""></a>          <span class="at">calendar =</span> calendars<span class="sc">$</span>utopia_seasons)   <span class="co"># -&gt; forwarded to interpolation</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p>The scenario folder name records what was swapped — <code>{scenario}_{model}_{calendar}_{horizon}</code> — computed from the <strong>final</strong> settings, so a substituted calendar shows up in the path:</p>
<pre><code>COARSE_UTOPIA_utopia-seasons_base/</code></pre>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Not yet <span class="badge planned">planned</span></strong></p>
</div>
<div class="callout-content">
<p>Swapping <strong>regions</strong>, and named scalar overrides such as <code>interpolate_model(mod, "S", discount = 0.07)</code>. Both are TODOs in the pipeline; for now, pass a full <code>config</code>/<code>settings</code> object.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="scale-data-and-models" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>8 · Scale: data and models</h1>

</section>
<section id="how-big-is-this-model" class="slide level2 smaller">
<h2>How big is this model?</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href=""></a><span class="fu">model_size</span>(scen_u, <span class="at">top_n =</span> <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>model_size: BASE
  parameters : 128 value, 233 maps, 13 sets
  param rows : 5,902
  estimate   : ~16,111 variables, ~16,832 constraints (from gating maps)
  top parameters by rows:
    pTechCinp2use      1,536
    pWeather           1,004
    pSliceWeight       404
    pSliceAgg          400
    pDemand            384</code></pre>
</div>
</div>
<p><code>model_size()</code> counts parameter rows and <strong>estimates</strong> variables and constraints from the gating maps — enough to decide whether a run is worth starting.</p>
</section>
<section id="four-ways-to-make-it-smaller" class="slide level2 smaller">
<h2>Four ways to make it smaller</h2>
<div class="small-table">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Operation</th>
<th>What it does</th>
<th>Lossless?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>prune</strong></td>
<td>drops rows whose value equals the parameter’s default</td>
<td>yes — an absent tuple reads back as the default</td>
</tr>
<tr class="even">
<td><strong>fold</strong></td>
<td>replaces a whole column with <code>NA</code> wildcards where the value does not vary across the <em>entire</em> allowed membership</td>
<td>yes — reversible with <code>unfold_*</code></td>
</tr>
<tr class="odd">
<td><strong>trim</strong></td>
<td>drops rows that no equation-domain map indexes, i.e.&nbsp;data the model never reads</td>
<td>yes</td>
</tr>
<tr class="even">
<td><strong>densify</strong></td>
<td>the <strong>opposite</strong> — materialises default rows, because GAMS has no parameter default and reads an absent tuple as <code>0</code></td>
<td>n/a</td>
</tr>
</tbody>
</table>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href=""></a><span class="fu">interpolate_model</span>(mod, <span class="st">"BASE"</span>,</span>
<span id="cb53-2"><a href=""></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,   <span class="co"># the storage knob: drop defaults, enable folding</span></span>
<span id="cb53-3"><a href=""></a>                  <span class="at">prune  =</span> <span class="cn">TRUE</span>,</span>
<span id="cb53-4"><a href=""></a>                  <span class="at">fold   =</span> <span class="fu">c</span>(<span class="st">"region"</span>, <span class="st">"slice"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><span class="badge limited">GLPK / JuMP / Pyomo only</span> — folding writes an artificial set member (<code>ANYREGION</code>, <code>ANYSLICE</code>, …) into the model source, and the substitution is not GAMS-ready yet.</p>
</div>
</section>
<section id="the-cheapest-reduction-is-a-sampled-calendar" class="slide level2 smaller">
<h2>The cheapest reduction is a sampled calendar</h2>
<p>Keep the same time <em>structure</em>, solve a representative <strong>subset</strong> of its slices — here every fourth hour of each season, and <code>year_fraction</code> records what is covered:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href=""></a>tt    <span class="ot">&lt;-</span> calendars<span class="sc">$</span>utopia_s4h24<span class="sc">@</span>timetable</span>
<span id="cb54-2"><a href=""></a>keep  <span class="ot">&lt;-</span> tt[<span class="fu">grepl</span>(<span class="st">"h(00|04|08|12|16|20)$"</span>, tt<span class="sc">$</span>HOUR), ]</span>
<span id="cb54-3"><a href=""></a>cal_s <span class="ot">&lt;-</span> <span class="fu">newCalendar</span>(<span class="at">name =</span> <span class="st">"utopia_s4h24_sampled"</span>, <span class="at">timetable =</span> keep,</span>
<span id="cb54-4"><a href=""></a>                     <span class="at">year_fraction =</span> <span class="fu">sum</span>(keep<span class="sc">$</span>share))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">scenario</th>
<th style="text-align: left;">calendar</th>
<th style="text-align: right;">slices</th>
<th style="text-align: left;">param_rows</th>
<th style="text-align: left;">variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">BASE</td>
<td style="text-align: left;">utopia_s4h24</td>
<td style="text-align: right;">96</td>
<td style="text-align: left;">5,902</td>
<td style="text-align: left;">16,111</td>
</tr>
<tr class="even">
<td style="text-align: left;">SAMPLED</td>
<td style="text-align: left;">utopia_s4h24_sampled</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;">1,614</td>
<td style="text-align: left;">4,231</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<p>A factor of roughly <strong>4×</strong> in rows and variables, from one substituted object. Reduce the <em>model</em> before reaching for storage tricks.</p>
</div>
</section>
<section id="sampling-vs-aggregation" class="slide level2 smaller">
<h2>Sampling vs aggregation</h2>
<p>Two different things, and only one of them exists today:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>What it does</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sampling</strong></td>
<td>solve a <em>subset</em> of the calendar’s slices; <code>year_fraction</code> scales annual quantities</td>
<td>works — substitute a sampled calendar</td>
</tr>
<tr class="even">
<td><strong>Aggregation</strong></td>
<td>roll a fine calendar’s data <em>up</em> onto a coarser one — reweighting profiles, load curves, availability</td>
<td><span class="badge planned">in development</span></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Passing a structurally different, coarser calendar will build a smaller model, but the fine-resolution data is <strong>not aggregated onto it</strong> — that machinery is still being written, and lands with the <strong>timescales</strong> package. Until then, sampling is the supported way to shrink the time dimension of an existing model.</p>
<p>Aggregation on the <strong>results</strong> side already works: <code>getData(timeframe = )</code> (Part 2).</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Whichever route you take, <code>compare_interp_settings()</code> and <code>compare_solve_settings()</code> rebuild the same model across a grid of <code>fold</code>/<code>sparse</code>/<code>prune</code> settings and check the <strong>objective is invariant</strong> — the check worth running before trusting a reduction.</p>
</div>
</div>
</div>
</div>
</section>
<section id="large-datasets-in-memory-or-on-disk" class="slide level2 smaller">
<h2>Large datasets: in memory or on disk</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href=""></a><span class="fu">interpolate_model</span>(mod, <span class="st">"BIG"</span>, <span class="at">ondisk =</span> <span class="cn">TRUE</span>)   <span class="co"># parameters written to disk</span></span>
<span id="cb55-2"><a href=""></a><span class="fu">save_scenario</span>(scen, <span class="at">path =</span> <span class="st">"scenarios/BIG"</span>)    <span class="co"># scenario spilled to parquet</span></span>
<span id="cb55-3"><a href=""></a><span class="fu">load_scenario</span>(<span class="st">"scenarios/BIG"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong><code>ondisk = TRUE</code></strong> writes each parameter to a <code>modInp/</code> folder instead of holding it in <code>@data</code>.</li>
<li><strong><code>save_scenario()</code></strong> stores data-frame slots as <strong>parquet</strong> (zstd by default) and empties the in-memory slots; <code>isInMemory()</code> tells you which state an object is in.</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Two honest caveats</strong></p>
</div>
<div class="callout-content">
<p><code>ondisk</code> reduces peak memory <strong>during the build only</strong> — everything is materialised back into RAM before the solver files are written.</p>
<p>And <code>getData()</code> <strong>collects eagerly</strong>: the Arrow dataset is opened lazily, but filtering happens in R afterwards. There is no predicate push-down, so this is not larger-than-memory querying.</p>
</div>
</div>
</div>
</section>
<section id="trimming-variables-planned" class="slide level2 smaller">
<h2>Trimming variables <span class="badge planned">planned</span></h2>
<p>Everything above operates on <strong>parameter rows</strong>. Removing the <em>variables</em> and <em>equations</em> those rows would have gated is a different job — an equation-graph cascade: mark empty-domain variables, untrim the ones still referenced, drop the rest.</p>
<p>That cascade lives in the sibling <strong>multimod</strong> package (<code>trim_model()</code>, <code>mark_empty_variables()</code>, <code>untrim_required_elements()</code>), and energyRt does not call it yet. A partial removal on the energyRt side would leave dangling variable references in the equations that read them — which is precisely why it is not attempted here.</p>
<p>Integration with multimod is in progress and is the route by which this arrives.</p>
</section></section>
<section>
<section id="reading-results" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>9 · Reading results</h1>

</section>
<section id="getdata-one-accessor-many-sources" class="slide level2 smaller">
<h2><code>getData()</code> — one accessor, many sources</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href=""></a><span class="fu">getData</span>(scen,  <span class="at">name =</span> <span class="st">"vTechAct"</span>)        <span class="co"># a solved scenario: results</span></span>
<span id="cb56-2"><a href=""></a><span class="fu">getData</span>(mod,   <span class="at">name =</span> <span class="st">"invcost"</span>)         <span class="co"># a model: raw input data, pre-interpolation</span></span>
<span id="cb56-3"><a href=""></a><span class="fu">getData</span>(ECOA,  <span class="at">name =</span> <span class="st">"ceff"</span>)            <span class="co"># a single object: its own slots</span></span>
<span id="cb56-4"><a href=""></a><span class="fu">getData</span>(<span class="fu">list</span>(<span class="at">BASE =</span> s1, <span class="at">CAP =</span> s2))       <span class="co"># a named list: stacked, with a `scenario` column</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Key arguments: <code>timeframe</code> and <code>geolevel</code> (aggregation, Parts 2–3), <code>merge</code>, <code>process</code>, <code>parameters</code>, <code>variables</code>, <code>drop.zeros</code>, <code>asTibble</code>.</p>
<div class="fragment">
<p>The <strong>named list</strong> form is how many scenarios are compared — there is no need for a registry to hold them.</p>
</div>
</section>
<section id="mixes-and-comparisons" class="slide level2 smaller">
<h2>Mixes and comparisons</h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href=""></a><span class="fu">autoplot</span>(scen_u)              <span class="co"># generation / capacity mixes</span></span>
<span id="cb57-2"><a href=""></a><span class="fu">getMix</span>(<span class="fu">list</span>(<span class="at">BASE =</span> scen_u, <span class="at">SAMPLED =</span> scen_s))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>getMix()</code> is the tidy extractor behind the scenario plot. Given a <strong>named list</strong> it row-binds with a <code>scenario</code> column, so any <code>ggplot2</code> comparison is a <code>facet_wrap(~ scenario)</code> away.</p>
<p><code>autoplot()</code> itself takes a single scenario — build multi-scenario charts from <code>getMix()</code>.</p>
</div><div class="column" style="width:52%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="builders_files/figure-revealjs/unnamed-chunk-73-1.png" width="780"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="levelized-costs-and-reports" class="slide level2 smaller">
<h2>Levelized costs and reports</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href=""></a>lc <span class="ot">&lt;-</span> <span class="fu">levcost</span>(scen_u, <span class="at">name =</span> <span class="st">"ECOA"</span>)</span>
<span id="cb58-2"><a href=""></a><span class="fu">autoplot</span>(lc, <span class="at">type =</span> <span class="st">"components"</span>)   <span class="co"># also: npv, totals, frontier, input_frontier</span></span>
<span id="cb58-3"><a href=""></a></span>
<span id="cb58-4"><a href=""></a><span class="fu">report</span>(scen_u)                       <span class="co"># results overview -&gt; HTML</span></span>
<span id="cb58-5"><a href=""></a><span class="fu">report</span>(mod_u)                        <span class="co"># full model report: config, inventory, every technology</span></span>
<span id="cb58-6"><a href=""></a><span class="fu">report</span>(ECOA, <span class="at">format =</span> <span class="st">"pdf"</span>)         <span class="co"># a single technology datasheet</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><code>report()</code> works on a <code>technology</code>, <code>repository</code>, <code>model</code> or solved <code>scenario</code>.</li>
<li>Formats: <code>html</code>, <code>pdf</code>, <code>tex</code> — it downgrades to HTML with a warning if no LaTeX engine is found.</li>
<li><strong>Templates are customisable</strong>: pass the absolute path of your own <code>.Rmd</code> to <code>template =</code>. The built-ins live in <code>inst/templates/</code> (<code>report_generic</code>, <code>report_model</code>, <code>report_scenario</code>, <code>report_vehicle</code>).</li>
</ul>
</section></section>
<section>
<section id="how-it-is-solved" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>10 · How it is solved</h1>

</section>
<section id="one-solution-type-today" class="slide level2 smaller">
<h2>One solution type today</h2>
<p>energyRt writes <strong>one linear program over all milestone years and solves it once</strong>: full <strong>perfect foresight</strong>. Every backend template contains a single solve statement.</p>
<p>That is a modelling assumption, not an implementation detail — the model knows the whole future when it invests. It is the right default for a least-cost benchmark and the wrong one for studying myopic behaviour.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Under development <span class="badge planned">planned</span></strong></p>
</div>
<div class="callout-content">
<p>Myopic · myopic with a guide or target · isolated regional solves · geo-aggregated solves · free/no-trade solves.</p>
<p>Also listed alongside these: <strong>coarse-time</strong> solving, which needs the aggregation machinery described in Part 8 — in development.</p>
<p><strong>Time-sampled</strong> solving is the one you can already do today, by substituting a sampled calendar (Parts 2, 7 and 8).</p>
</div>
</div>
</div>
</section>
<section id="backends-and-solvers" class="slide level2 smaller">
<h2>Backends and solvers</h2>
<div class="columns">
<div class="column" style="width:52%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Backend</th>
<th>Needs locally</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>GLPK / MathProg</strong></td>
<td><code>glpsol</code> (ships with Rtools)</td>
</tr>
<tr class="even">
<td><strong>Julia / JuMP</strong></td>
<td>Julia + HiGHS</td>
</tr>
<tr class="odd">
<td><strong>Python / Pyomo</strong></td>
<td>Python + CBC/HiGHS</td>
</tr>
<tr class="even">
<td><strong>GAMS</strong></td>
<td>GAMS + a license</td>
</tr>
<tr class="odd">
<td><strong>NEOS</strong></td>
<td><em>nothing</em> — an email address</td>
</tr>
</tbody>
</table>
<p>The same model object solves on any of them.</p>
</div><div class="column" style="width:48%;">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href=""></a>solver_options<span class="sc">$</span>glpk</span>
<span id="cb59-2"><a href=""></a>solver_options<span class="sc">$</span>julia_highs_barrier</span>
<span id="cb59-3"><a href=""></a>solver_options<span class="sc">$</span>neos_gams_cplex</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>26 presets ship with the package. NEOS submits the model as inlined text, so a CPLEX solve needs no local GAMS at all — subject to its academic/non-commercial terms and a ~16 MB job cap.</p>
<p>Cross-solving one scenario on two backends and comparing objectives is the strongest correctness check available.</p>
</div></div>
</section></section>
<section>
<section id="methods-at-a-glance" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>11 · Methods at a glance</h1>

</section>
<section id="what-you-can-call-on-what" class="slide level2 smaller">
<h2>What you can call on what</h2>
<div class="small-table">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Returns</th>
<th>Defined for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>draw()</code></td>
<td>grid schematic</td>
<td><code>technology</code>, <code>storage</code>, <code>supply</code>, <code>demand</code>, <code>import</code>, <code>export</code>, <code>trade</code></td>
</tr>
<tr class="even">
<td><code>autoplot()</code></td>
<td><strong>ggplot</strong></td>
<td>19 classes — <code>calendar</code>, <code>horizon</code>, <code>commodity</code>, <code>weather</code>, <code>trade</code>, <code>demand</code>, the processes, <code>levcost</code>, <code>scenario</code>, <code>model</code>, <code>repository</code></td>
</tr>
<tr class="odd">
<td><code>plot()</code></td>
<td>ggplot</td>
<td>17 classes — a thin delegate to <code>autoplot()</code></td>
</tr>
<tr class="even">
<td><code>getData()</code></td>
<td>tidy data</td>
<td>scenarios (and lists of them), models, repositories, single objects</td>
</tr>
<tr class="odd">
<td><code>getObject()</code></td>
<td>the objects</td>
<td>repository, model, scenario — filtered by class, name, region, …</td>
</tr>
<tr class="even">
<td><code>report()</code></td>
<td>html / pdf / tex</td>
<td><code>technology</code>, <code>repository</code>, <code>model</code>, <code>scenario</code></td>
</tr>
<tr class="odd">
<td><code>design()</code></td>
<td>R code</td>
<td><code>technology</code> <span class="badge limited">only</span></td>
</tr>
<tr class="even">
<td><code>summary()</code> / <code>show()</code></td>
<td>console</td>
<td><code>model</code>, <code>scenario</code>, <code>repository</code> <span class="badge limited">only</span></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>Two things worth knowing before you go looking: there is <strong>no <code>draw()</code> for a model or repository</strong> — <code>draw()</code> describes a process, and <code>report(mod)</code> is what describes a whole model. And a process <code>autoplot()</code> needs year-indexed data in the economics or capacity slots; with none it returns <code>NULL</code> and says so.</p>
</div>
</section>
<section id="the-workhorses" class="slide level2 smaller">
<h2>The workhorses</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>While building</strong></p>
<ul>
<li><code>draw(obj)</code> — is this the system I meant?</li>
<li><code>design(tech)</code> — what does this object actually say?</li>
<li><code>getObject(repo, class = "technology")</code> — what is in here?</li>
<li><code>autoplot(cal)</code>, <code>autoplot(hor)</code> — is the time structure right?</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>After solving</strong></p>
<ul>
<li><code>autoplot(scen)</code> — the mixes</li>
<li><code>getMix(list(...))</code> — compare scenarios</li>
<li><code>levcost(scen, name =)</code> — why did it pick that?</li>
<li><code>model_size(scen)</code> — why is this so slow?</li>
<li><code>report(scen)</code> — everything, in one document</li>
</ul>
</div></div>
</section></section>
<section>
<section id="extending" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>12 · Extending</h1>

</section>
<section id="your-own-constraints" class="slide level2 smaller">
<h2>Your own constraints</h2>
<p>The escape hatch that avoids forking the model code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href=""></a><span class="fu">newConstraint</span>(</span>
<span id="cb60-2"><a href=""></a>  <span class="at">name  =</span> <span class="st">"RES_SHARE"</span>,</span>
<span id="cb60-3"><a href=""></a>  <span class="at">eq    =</span> <span class="st">"&gt;="</span>,</span>
<span id="cb60-4"><a href=""></a>  <span class="fu">list</span>(<span class="at">variable =</span> <span class="st">"vTechOut"</span>, <span class="at">for.sum =</span> <span class="fu">list</span>(<span class="at">tech =</span> <span class="fu">c</span>(<span class="st">"EWIN"</span>, <span class="st">"ESOL"</span>))),</span>
<span id="cb60-5"><a href=""></a>  <span class="at">rhs   =</span> <span class="fu">data.frame</span>(<span class="at">year =</span> <span class="fu">c</span>(<span class="dv">2030</span>, <span class="dv">2050</span>), <span class="at">rhs =</span> <span class="fu">c</span>(<span class="fl">0.3</span>, <span class="fl">0.6</span>))</span>
<span id="cb60-6"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<blockquote>
<p><em>In many cases this can be done without writing constraints in the GAMS, Julia/JuMP, Python/Pyomo, or GLPK-MathProg languages.</em></p>
</blockquote>
<p>Each left-hand-side term is a <strong>summand</strong>: a <code>variable</code>, a multiplier <code>mult</code>, and what to sum it <code>for.sum</code> over.</p>
<p><span class="badge exp">experimental</span> — and user constraints currently compile to GAMS-dialect text; moving them to a language-neutral form so every backend renders from one definition is in progress.</p>
</section>
<section id="the-other-extension-points" class="slide level2 smaller">
<h2>The other extension points</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Want to</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>add a relationship between variables</td>
<td><code>newConstraint()</code> <span class="badge exp">experimental</span></td>
</tr>
<tr class="even">
<td>add a cost term to the objective</td>
<td><code>newCosts()</code> <span class="badge exp">experimental</span></td>
</tr>
<tr class="odd">
<td>change what a report shows</td>
<td><code>report(template = "/path/to/your.Rmd")</code></td>
</tr>
<tr class="even">
<td>carry your own metadata on any object</td>
<td>the <code>@misc</code> slot — never read by the model</td>
</tr>
<tr class="odd">
<td>change solver behaviour</td>
<td><code>solver_options$...</code>, or <code>set_option()</code> / <code>en_config_write()</code></td>
</tr>
<tr class="even">
<td>add a new mapping to the pipeline</td>
<td>the mapping registry — a <em>contributor</em> path: declare it in <code>modInp.yml</code>, write <code>map_&lt;Name&gt;()</code>, register it</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Not available yet: <strong><code>newVariable()</code></strong> <span class="badge planned">planned</span>. The variable catalogue is fixed; a runtime constructor paralleling <code>newConstraint()</code> is on the roadmap. (The <code>variable</code> class you can see is the results container, not a constructor.)</p>
</div>
</section></section>
<section>
<section id="where-this-is-going" class="title-slide slide level1 center" data-background-color="#f4f4f4">
<h1>13 · Where this is going</h1>

</section>
<section id="roadmap" class="slide level2 smaller">
<h2>Roadmap</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Structure</strong></p>
<ul>
<li>Nested <strong>regions</strong> via <code>geoscales</code> and nested <strong>time</strong> via <code>timescales</code> — today both are flat sets with aggregation only on the reporting side</li>
<li><code>newVariable()</code>, to match <code>newConstraint()</code></li>
<li>Language-neutral user constraints, rendered to every backend from one definition</li>
<li>Physical properties on <code>commodity</code> (mass, volume, heating value)</li>
<li>Region swapping and scalar setting overrides in scenario definition</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Scale and solving</strong></p>
<ul>
<li>Alternative solution types — myopic first</li>
<li>multimod integration: the variable/equation <strong>trim</strong> cascade, and one shared model definition across packages</li>
<li>Lazy, push-down querying of on-disk results</li>
<li>Scenario <strong>registry</strong> — a working index over many saved scenarios <span class="badge exp">experimental today</span></li>
</ul>
</div></div>
<div class="fragment">
<p>Most of the packages around energyRt are pre-release. If a piece of this is on your critical path, say so — that is the most useful thing you can tell us.</p>
</div>
</section>
<section id="recap" class="slide level2 smaller scrollable">
<h2>Recap</h2>
<div class="columns">
<div class="column" style="width:50%;">
<ol type="1">
<li><strong>Objects</strong> describe the system — <code>new*()</code>, one grammar throughout</li>
<li><strong>Calendars and horizons</strong> decide where those objects live in time; <strong>regions and geoscales</strong>, in space</li>
<li><strong>Vintages and clusters</strong> put many variants on one object</li>
<li><strong>Interpolation</strong> turns anchors into a full grid</li>
</ol>
</div><div class="column" style="width:50%;">
<ol start="5" type="1">
<li><strong>Scenarios</strong> are the same model with objects substituted</li>
<li><strong>Scale</strong> is managed first by sampling the calendar, then by pruning, folding and trimming its data</li>
<li><strong>Results</strong> come back tidy — <code>getData()</code>, <code>autoplot()</code>, <code>levcost()</code>, <code>report()</code></li>
</ol>
</div></div>
<div class="fragment">
<p><strong>When in doubt, <code>draw()</code> it</strong> — and when the model is slow, <code>model_size()</code> it.</p>

</div>
</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>energyRt · useR! Training</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="builders_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="builders_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="builders_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="builders_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="builders_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="builders_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="builders_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="builders_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="builders_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="builders_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 6.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>